theme: jekyll-theme-minimal
Hej. Dette er en test af en hjemmeside. 
Nedenfor er eksempler på apps til din telefon der kan forbedre læringen i samarbejde med dine børn: 
App 1
App 2
App 3
App 4
App 5
App 6
